### ISSUE TITLE
Need help on how to know the pattern of insertion

### ISSUE THREAD

**Issue by mechazod** [PeculiarVentures/graphene#94]
I had tried to insert 7 item and each insertion i tried to execute encryption to know if the slot and PIN is match. However, i conclude that softhsm has a random insertion, i dont have a clue. But everytime I insert is I detect the next slot to add to the init token command. 

Thank you in advance people :)

**Comment by microshine** [comment]
@mechazod Can you share code?

**Comment by mechazod** [comment]
![screen shot 2018-03-11 at 7 25 09 pm](https://user-images.githubusercontent.com/16739905/37252779-78e87620-2562-11e8-92ef-b5f235af9d21.png)
![screen shot 2018-03-11 at 7 25 57 pm](https://user-images.githubusercontent.com/16739905/37252782-7e1e13b6-2562-11e8-829d-fd3bd21c4035.png)
![screen shot 2018-03-11 at 7 26 28 pm](https://user-images.githubusercontent.com/16739905/37252783-7eaf3738-2562-11e8-9052-e1dddef6dc63.png)
![screen shot 2018-03-11 at 7 26 33 pm](https://user-images.githubusercontent.com/16739905/37252785-7f57b336-2562-11e8-9de3-1da7a34d27a6.png)

--show-slots
![screen shot 2018-03-11 at 7 27 24 pm](https://user-images.githubusercontent.com/16739905/37252789-9d29aab8-2562-11e8-8cb6-6133a2b991f4.png)

//current arrangement of slots
![screen shot 2018-03-11 at 7 30 46 pm](https://user-images.githubusercontent.com/16739905/37252795-d0a3e37c-2562-11e8-97c5-546b83533c5a.png)

**Comment by microshine** [comment]
As I can see SoftHSM2 adds new slot at the beginning of the slot list
I created simple JS which demonstrates it. 

```js
//@ts-check
const graphene = require("graphene-pk11");
const child_process = require("child_process");

function exec(cmd) {
    return new Promise((resolve, reject) => {
        child_process.exec(cmd, (err, stdout, stderr) => {
            if (err) {
                reject(err);
            } else if (stderr) {
                reject(new Error(stderr));
            } else {
                resolve(stdout);
            }
        });
    });
}

class SlotHelper {

    constructor() {
        this.hsm = graphene.Module.load("/usr/local/lib/softhsm/libsofthsm2.so", "SoftHSM2");
        this.hsm.initialize();
    }

    GetCount() {
        return this.hsm.getSlots(true).length;
    }

    PrintInfo(slotIndex) {
        const slot = this.hsm.getSlots(slotIndex, true);
        const token = slot.getToken();
        console.log(`Slot #${slotIndex}`);
        console.log(`  Handle: ${slot.handle.toString("hex")}`);
        console.log(`  Description: ${slot.slotDescription}`);
        console.log(`  Label: ${token.label}`);
        console.log(`  Serial: ${token.serialNumber}`);
    }

    InitToken(slot, label, soPin, pin) {
        return exec(`softhsm2-util --init-token --free --label "${label}" --so-pin=${soPin} --pin=${pin}`);
    }
 
    Reset() {
        this.hsm.finalize();
        this.hsm.initialize();
    }
}

async function main() {
    const hsmHelper = new SlotHelper();

    let count = hsmHelper.GetCount()
    console.log("Slot count:", count);
    console.log();

    for (let i = 0; i < count; i++) {
        hsmHelper.PrintInfo(i);
        console.log();
    }

    const initOut = await hsmHelper.InitToken(count, `Test slot ${++count}`, "888888", `password${count}`);
    console.log("Slot added\n", initOut);
    hsmHelper.Reset();

    console.log("Slot count:", count);
    console.log();

    for (let i = 0; i < count; i++) {
        hsmHelper.PrintInfo(i);
        console.log();
    }
}

main()
    .catch((err) => {
        console.error(err);
    })
```

### Output
```
Slot count: 3

Slot #0
  Handle: 1b1e136f00000000
  Description: SoftHSM slot ID 0x6f131e1b
  Label: My slot 2
  Serial: c7d11fb26f131e1b

Slot #1
  Handle: 3c9ac87000000000
  Description: SoftHSM slot ID 0x70c89a3c
  Label: My slot 0
  Serial: 40091ac070c89a3c

Slot #2
  Handle: 0200000000000000
  Description: SoftHSM slot ID 0x2
  Label:
  Serial:

Slot added
 Slot 2 has a free/uninitialized token.
The token has been initialized and is reassigned to slot 662168012

Slot count: 4

Slot #0
  Handle: cce1772700000000
  Description: SoftHSM slot ID 0x2777e1cc
  Label: Test slot 4
  Serial: 65dafa4c2777e1cc

Slot #1
  Handle: 1b1e136f00000000
  Description: SoftHSM slot ID 0x6f131e1b
  Label: My slot 2
  Serial: c7d11fb26f131e1b

Slot #2
  Handle: 3c9ac87000000000
  Description: SoftHSM slot ID 0x70c89a3c
  Label: My slot 0
  Serial: 40091ac070c89a3c

Slot #3
  Handle: 0300000000000000
  Description: SoftHSM slot ID 0x3
  Label:
  Serial:
```
